### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by thobass** [thobass/SODA-Console-CSharp#1]
## Couche de présentation :
- [x] Construction du menu
- [ ] Lecture des choix avec gestion des erreurs
- [ ] Invitation à un autre choix avec gestion des erreurs
- [ ] Injection de dépendances

## Couche métier :
- [ ] Implémentation des beans (POCO) dans le répertoire beans
- [ ] Implémentation des services pour manipuler les objets métiers
- [ ] Gestion des erreurs

## Couche de persistance avec nhibernate :
- [ ] Création de la base de donnée postgresql
- [ ] Mapping des POCOS avec l'ORM
- [ ] Injection de dépendances
